- hosts: "*"
  become: yes
  gather_facts: true
  tasks:
  - name: Create ansible user and add to root group
    user:
      name: "ansible"
      groups: "root"
  
  - name: Add ansible user to sudoers - Debian/Ubuntu
    copy:
      dest: "/etc/sudoers.d/ansible"
      content: "ansible   ALL=(ALL)   NOPASSWD:   ALL"
    when: ansible_os_family == "Debian"

  - name: Add ansible user to sudoers - Rocky/RedHat
    copy:
      dest: "/etc/sudoers
      content: "ansible   ALL=(ALL)   NOPASSWD:   ALL"
    when: ansible_os_family == "RedHat"

  - name: Add authorized keys
    authorized_key:
      user: "ansible"
      key: "/home/ansible/.ssh/id_rsa.pub"

  - name: Disable Password Authentication
    lineinfile:
      dest: /etc/ssh/sshd_config
      regexp: '^PasswordAuthentication'
      line: "PasswordAuthentication no"
      state: present
      backup: yes

  - name: "Restart ssh - Debian/Ubuntu"
    service:
      name: ssh
      state: restarted
    when: ansible_os_family == "Debian"

  - name: "Restart sshd - Rocky/RedHat"
    service:
      name: sshd
      state: restarted
    when: ansible_os_family == "RedHat"