- hosts: "*"
  become: yes
  gather_facts: true
  tasks:

    - name: Run Ubuntu distribution upgrade to current latest
      shell: do-release-upgrade -f DistUpgradeViewNonInteractive
    
    - name: Check if a reboot is required.
      ansible.builtin.stat:
        path: /var/run/reboot-required
        get_md5: no
      register: reboot_required_file

    - name: Reboot the server (if required).
      ansible.builtin.reboot:
      when: reboot_required_file.stat.exists == true